// Auto-generated by VIP Connect Bot — do not edit manually
// To update, post changes in the event's Slack channel

export const eventConfig = {
  "city": "New York City",
  "venue": "MetLife Stadium",
  "capacity": 20,
  "eventTitle": "VIP Connect — New York City Leadership Dinner",
  "heroImageUrl": "/venue/long-table.png",
  "heroHeadline": "VIP Connect",
  "heroSubheadline": "New York City Leadership Dinner",
  "heroDescription": "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",
  "experienceHeadline": "Twenty leaders.\\nVIP suites during the World Cup.\\nNo slides.",
  "experienceParagraphs": [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other’s assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What’s working, what’s not, and what the next twelve months look like.",
    "We gather at MetLife Stadium in exclusive VIP suites during one of the world's premier sporting events."
  ],
  "agendaItems": [
    {
      "time": "7:00 PM",
      "title": "Arrival & Welcome Drinks",
      "description": "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small."
    },
    {
      "time": "7:30 PM",
      "title": "Executive Session",
      "description": "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like."
    },
    {
      "time": "7:45 PM",
      "title": "Dinner",
      "description": "A curated dinner experience with premium beverages served throughout the World Cup match."
    },
    {
      "time": "10:00 PM",
      "title": "Event Close",
      "description": "An informal close as the evening winds down."
    }
  ],
  "agendaShort": [
    {
      "time": "7:00 PM",
      "label": "Arrival & welcome drinks"
    },
    {
      "time": "7:30 PM",
      "label": "Executive session"
    },
    {
      "time": "7:45 PM",
      "label": "Dinner"
    },
    {
      "time": "10:00 PM",
      "label": "Event close"
    }
  ],
  "faqItems": [
    {
      "q": "What is Moloco VIP Connect?",
      "a": "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion."
    },
    {
      "q": "Who is this event for?",
      "a": "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 20 people. Small enough that everyone speaks, diverse enough that you’ll hear something that changes how you think about a problem."
    },
    {
      "q": "Is this a public event / can I bring a +1?",
      "a": "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link."
    },
    {
      "q": "What should I wear?",
      "a": "Smart casual. Polished but comfortable. Think what you’d wear to dinner with people you want to impress without looking like you tried."
    },
    {
      "q": "Is there a cost to attend?",
      "a": "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco."
    },
    {
      "q": "What about dietary requirements?",
      "a": "MetLife Stadium accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they’ll take care of it."
    }
  ],
  "calendarTitle": "Moloco VIP Connect — New York City Leadership Dinner",
  "calendarUidPrefix": "moloco-vip-connect-2026",
  "siteUrl": "https://moloco-event-new-york-city.vercel.app",
  "slug": "moloco-event-new-york-city",
  "eventSubtitle": "An exclusive World Cup experience with enterprise leaders",
  "venueAddress": "1 MetLife Stadium Dr, East Rutherford, NJ 07073",
  "venueAddressFull": "1 MetLife Stadium Drive, East Rutherford, NJ 07073, United States",
  "date": "June 20, 2024",
  "dateFull": "Thursday, June 20",
  "dateISO": "2024-06-20",
  "calendarDateStart": "20240620T190000",
  "calendarDateEnd": "20240620T220000",
  "time": "7:00 PM",
  "timezone": "America/New_York",
  "timezoneAbbr": "EDT",
  "venueDescription": "MetLife Stadium stands as one of the world's premier sporting venues, hosting the biggest games on the global stage. Our private VIP suites offer floor-to-ceiling windows with commanding views of the pitch, premium furnishings, and dedicated service staff. The atmosphere during World Cup matches creates an unparalleled backdrop for meaningful business connections.",
  "venueCapacityNote": "Our private VIP suite accommodates twenty guests with premium seating and dedicated hospitality service.",
  "venueDiningNote": "A curated dinner menu is served alongside premium beverages throughout the evening.",
  "venueDirections": "MetLife Stadium is accessible via NJ Transit rail to Secaucus Junction, then transfer to stadium shuttle service. The venue is located in East Rutherford, approximately 8 miles west of Manhattan. VIP entrance and dedicated parking are available for suite guests.",
  "venueExperienceLine": "We gather at MetLife Stadium in exclusive VIP suites during one of the world's premier sporting events.",
  "dinnerDescription": "A curated dinner experience with premium beverages served throughout the World Cup match.",
  "mapsUrl": "https://maps.google.com/maps?q=MetLife+Stadium,+1+MetLife+Stadium+Dr,+East+Rutherford,+NJ+07073"
};
